### ISSUE TITLE
README could be improved

### ISSUE THREAD

**Issue by machty** [socketry/db-postgres#5]
I've been using the now-archived async-postgres for a while and I've been referred to this repo as its replacement, but I'm not sure where to start and the README isn't too much help as is:

1. The README says this is "A light-weight wrapper for Ruby exposing libpq"; based on the name of the repo and and everything else I can see, there's no mention of this being an evented adapter, or whether/how it relates to the rest of the `async` ecosystem, or how/why this is different than the standard `pg` gem
2. I'm not sure whether I need to _do_ anything to start using this gem
3. What is [DB::Adapters](A light-weight wrapper for Ruby exposing libpq) and which gem declares/defines it?

**Comment by singpolyma** [comment]
Also would be nice to detail the benefits of this over just eg `pg` gem when under ruby3 with a fiber scheduler.
